name: Publish Docker

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@vmain
      - name: Publish to registy
        uses: elgohr/Publish-Docker-Github-Action@vmain
        with:
          registry: docker.pkg.github.com
          name: docker.pkg.github.com/RidiculousCircumstances/rating-api_purple-school/rating-api_container
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "develop"